config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :devices
  root to: 'techbits#index'
  resources :techbits
  resources :pushapps
  get '/audits/users', to: 'audits#users'

# Adding the User CRUD for admin to add, create, update and delete user using UI.
  scope module: 'admin' do
    resources :users
  end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      post 'authenticate', to: 'authentication#authenticate'
      get 'techbits/all', to: 'techbits#all'
      get 'techbits/active', to: 'techbits#active'
      #publish notification to specific device
      match 'publish_notification/', to: 'publish_notifications#create', via: [:post]
      match 'publish_notification/new', to: 'publish_notifications#new', via: [:get]
      match 'device_token/', to: 'device_token#create_or_update', via: [:put,:post]
    end
  end
end

app/models/pushapp.rb
class Pushapp < RailsPushNotifications::APNSApp 
  self.table_name = "rails_push_notifications_apns_apps"
end

app/controllers/pushapps_controller.rb
class PushappsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_app, only: [:show, :destroy, :edit, :update]

  def index
    @apps = Pushapp.all
  end

  def new
    @app = Pushapp.new
  end

  def create
    @app = Pushapp.new(apns_params)
    if @app.save
      flash[:notice] = "Successfully created APNS App" 
      redirect_to pushapps_path
    else
      render 'new', alert: "Unable to create APNS App"
    end 
  end

  def show
  end

  def edit
  end

  def update
    if @app.update(apns_params)
      flash[:notice] = "Successfully updated App"
      redirect_to @app
    else
      render 'edit', alert: "Unable to update App"
    end
  end

  def destroy
    if @app.destroy
      redirect_to pushapps_path, :notice => "Pushapp deleted successfully."
    else
      flash[:eroor] = "Unable to delete app"
      redirect_to pushapp_path(@app)
    end
  end

  private

  def apns_params
    params.require(:pushapp).permit(:name, :apns_dev_cert, :apns_prod_cert, :sandbox_mode)
  end

  def set_app
    @app = Pushapp.find(params[:id])
  end
end

app/views/pushapps/_form.html.erb
<%= simple_form_for @app do |f| %>
  <%= f.input :name %>
  <%= f.input :apns_dev_cert %>
  <%= f.input :apns_prod_cert %>
  <%= f.input :sandbox_mode, as: :boolean %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/pushapps/edit.html.erb
<%= render 'form' %>

app/views/pushapps/index.html.erb
<div class="table-responsive">
  <h1 class="text-center">APNS Apps</h1>
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">APNS Dev Certificate</th>
        <th scope="col">APNS Prod Ceritificate</th>
        <th scope="col">Sandbox Mode</th>
        <th scope="col">Created At</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @apps.each do |app| %>
      <tr>
        <td><%= app.name %></td>
        <td><%= truncate(app.apns_dev_cert, length: 50) %></td>
        <td><%= truncate(app.apns_prod_cert, length: 50) %></td>
        <td><%= app.sandbox_mode %></td>
        <td><%= app.created_at %></td>
        <td><%= link_to 'Show', pushapp_path(app), class: 'btn btn-dark' %></td>
        <td><%= link_to 'Delete', pushapp_path(app), data: {confirm: 'Are you sure?'}, method: :delete, class: 'btn btn-danger'%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= button_to "Create APNS App", new_pushapp_path, method: :get, class: "btn btn-primary float-right" %>

app/views/pushapps/new.html.erb
<%= form_tag pushapps_path do %>
  <label>Application Name</label>
  <%= text_field_tag :appname %>
  <label>APNS Dev Cert</label>
  <%= text_field_tag :apns_dev_cert %>
  <label>APNS Prod Cert</label>
  <%= text_field_tag :apns_prod_cert %>
  <%= submit_tag "Submit" %>
<% end %>

app/views/pushapps/show.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">APNS Development Certificate</th>
        <th scope="col">APNS Production Cetificate</th>
        <th scope="col">Sandbox Mode</th>
        <th scope="col">Created At</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @app.name %></td>
        <td><%= @app.apns_dev_cert %></td>
        <td><%= @app.apns_prod_cert %></td>
        <td><%= @app.sandbox_mode %></td>
        <td><%= @app.created_at %></td>
        <td><%= link_to 'Edit', edit_pushapp_path(@app), class: 'btn btn-dark' %></td>
        <td><%= link_to 'Delete', pushapp_path(@app), data: {confirm: 'Are you sure?'}, method: :delete, class: 'btn btn-danger'%></td>
      </tr>
    </tbody>
  </table>
</div>