config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :devices
  root to: 'techbits#index'
  resources :techbits
  resources :pushapps
  get '/audits/users', to: 'audits#users'

# Adding the User CRUD for admin to add, create, update and delete user using UI.
  scope module: 'admin' do
    resources :users
  end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      post 'authenticate', to: 'authentication#authenticate'
      get 'techbits/all', to: 'techbits#all'
      get 'techbits/active', to: 'techbits#active'
      #publish notification to specific device
      match 'publish_notification/', to: 'publish_notifications#create', via: [:post]
      match 'publish_notification/new', to: 'publish_notifications#new', via: [:get]
      match 'device_token/', to: 'device_token#create_or_update', via: [:put,:post]
    end
  end
end

app/models/techbit.rb
class Techbit < ApplicationRecord
  audited
  validates :title, presence: true
  validates :description, presence: true
  validates :url, presence: true
end

app/controllers/api/v1/techbits_controller.rb
require 'open-uri'
class API::V1::TechbitsController < ApiController
  before_action :load_json_file

   # Get all the records in the JSON file
  def all
    render json: @json_array
  end

  # Get only records which have active field set to true
  def active
    result = @json_array.select do |record|
      record["active"] == true
    end
    render json: result
  end

  private

  # Load the file from public assets directory
  # The json url is taken based on environment
  def load_json_file
    @json_array = Techbit.all
  end

  def techupdate_params
    params.permit(:techupdate).permit(:title, :description, :url, :active)
  end
end

app/controllers/techbits_controller.rb
class TechbitsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_techbit, only: [:show, :edit, :update, :destroy]

  # GET /techbits
  def index
    @techbits = Techbit.order(:created_at => "DESC").page
  end

  # GET /techbits/:id
  def show
  end

  # GET /techbits/new
  def new
    @techbit = Techbit.new
  end

  # POST /techbits
  def create
    @techbit = Techbit.new(techbit_params)
    if @techbit.save
      flash[:notice] = "Successfully created techbit."
      redirect_to @techbit
    else
      render 'new' , :alert => "Unable to create techbit!"
    end
  end

  # GET /techbits/:id/edit
  def edit
  end

  # PUT/PATCH /techbits/:id
  def update
    if @techbit.update(techbit_params)
      flash[:notice] = "Successfully updated techbit."
      redirect_to @techbit
    else
      render 'edit', :alert => "Unable to update techbit!"
    end
  end

  # DELETE /techbits/:id
  def destroy
    redirect_to techbits_path, :notice => "Techbit updated successfully." if @techbit.destroy
  end

  private

  # Don't trust the params from the internet. Whitelist all parameters
  def techbit_params
    params.require(:techbit).permit(:title, :description, :url, :active)
  end

  def set_techbit
    @techbit = Techbit.find(params[:id])
  end
end

app/views/techbits/_form.html.erb
<%= simple_form_for @techbit do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :url , label: "URL" %>
  <%= f.input :active, as: :boolean %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/techbits/edit.html.erb
  <%= render "form" %>

app/views/techbits/index.html.erb
<div class="table-responsive">
  <h1 class="text-center">Techbits</h1>
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">URL</th>
        <th scope="col">Active</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @techbits.each do |techbit| %>
      <tr>
        <td><%= techbit.created_at.strftime("%m-%d-%Y") %></td>
        <td><%= techbit.title %></td>
        <td><%= techbit.description %></td>
        <td><%= techbit.url %></td>
        <td><%= techbit.active %></td>
        <td><%= link_to 'Show', techbit_path(techbit), class: 'btn btn-dark' %></td>
        <td><%= link_to 'Delete', techbit_path(techbit), data: {confirm: 'Are you sure?'}, method: :delete, class: 'btn btn-danger'%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= button_to "Create Techbit", new_techbit_path, method: :get, class: "btn btn-primary float-right" %>
<%= paginate @techbits %>

app/views/techbits/new.html.erb
<%= render "form" %>

app/views/techbits/show.html.erb
  <div class="table-responsive">
    <table class="table table-striped table-bordered">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Title</th>
          <th scope="col">Description</th>
          <th scope="col">URL</th>
          <th scope="col">Active</th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @techbit.created_at.strftime("%m-%d-%Y") %></td>
          <td><%= @techbit.title %></td>
          <td><%= @techbit.description %></td>
          <td><%= @techbit.url %></td>
          <td><%= @techbit.active %></td>
          <td><%= link_to 'Back', techbits_path , class: 'btn btn-dark'%></td>
          <td><%= link_to 'Edit', edit_techbit_path(@techbit), class: 'btn btn-dark' %></td>
        </tr>
      </tbody>
    </table>
  </div>